name: "RPG_reloaded"
version: 0.1
description: Immensive Overhaul for Bukkit Servers
website: dev.bukkit.org
author: Frittenritter
main: me.frittenritter.rpgreloaded.RPGReloaded
depend: [Vault]

commands:
  rpgr:
    description: 'Main Command'
    usage: /<command>
    permission: rpgr.admin
    permission-message: 'No permission.'
permission-message: 'No permission.'